#! /usr/bin/env bash

main() {
	local files=*.rn

	for f in $files; do
		local i=${f//.rn/.s}
		local o=${f//.rn/.o}

		if [[ -f $i ]]; then
			rm $i
		fi

		if [[ -f $o ]]; then
			rm $o
		fi
	done
}

main
